---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubestronaut-predictor-deploy
  namespace: kubestronaut-predictor
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: github-credentials
  url: https://github.com/lfarizav/kubestronaut-predictor-deploy
