---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-deploy
  namespace: monitoring
spec:
  interval: 1m0s
  path: ./flux
  prune: false
  serviceAccountName: monitoring--source=GitRepository/kubestronaut-predictor-deploy
  sourceRef:
    kind: ""
    name: ""
