---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubestronaut-predictor-deploy-deploy
  namespace: monitoring
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/lfarizav/kubestronaut-predictor-deploy
